# backend Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements/*.txt ./requirements/
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade --no-cache-dir pip
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY . .

CMD celery -A wsgi.celery worker --loglevel=info --autoscale=9,2 & gunicorn -c gunicorn_config.py wsgi:app