"""empty message

Revision ID: 0f5cb299531a
Revises: 
Create Date: 2024-06-08 18:37:56.975465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f5cb299531a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.alter_column('json_data',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('total_income',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_expenses',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('net_growth',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_financial_reports_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_reports_created_at'))
        batch_op.alter_column('net_growth',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_expenses',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_income',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('json_data',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
